#!/bin/bash

if grep -q 'keggsmurph21/wt' ~/.bashrc; then
    exit
fi

PREFIX=~
install_dir="$PREFIX/.config/wt"
mkdir -p "$install_dir"

my_dir="$(dirname "$(realpath "$0")")"
cp "$my_dir/*.py" "$install_dir"

cat "$my_dir/wt.bash" \
    | sed -E "s,/path/to/wt,$install_dir," \
    > "$install_dir/wt.bash"

echo "# see https://github.com/keggsmurph21/wt
source \"$install_dir/wt.bash\"" >> ~/.bashrc
