#!/bin/bash

my_dir="$(dirname "$(realpath "$0")")"
cat "$my_dir/wt-template.bash" \
    | sed -E "s,__PATH_TO_WT=,__PATH_TO_WT=\"$my_dir/..\"," \
    > "$my_dir/wt.bash"

# TODO allow different bash files (e.g. .bash_profile for MacOS)
BASH_FILE="$HOME/.bashrc"

# idempotence
grep -q 'keggsmurph21/wt' $BASH_FILE || cat <<EOF>> $BASH_FILE
# see https://github.com/keggsmurph21/wt
source $my_dir/wt.bash
EOF

cat <<EOM
to complete installation, run in a terminal:
    $ . $BASH_FILE
EOM
