#!/bin/bash

# TODO allow different bash files (e.g. .bash_profile for MacOS)
#if grep -q 'keggsmurph21/wt' ~/.bashrc; then
#    exit # TODO do something smarter here
#fi

PREFIX=~ # TODO allow user to change this during installation
install_dir="$PREFIX/.config/wt"
mkdir -p "$install_dir"

my_dir="$(dirname "$(realpath "$0")")"
cp "$my_dir"/*.py "$my_dir/wt.bash" "$install_dir"
sed -i -E "s,/path/to/wt,$install_dir," "$install_dir/wt.bash"

#echo "
## see https://github.com/keggsmurph21/wt
#source \"$install_dir/wt.bash\"" >> ~/.bashrc
